eff_conv_noConv_noRecl_pre2:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/outData/FCCee_singleParticle_performace/gamma/FCCee_testConvertionDetection/fullTheta2/ 
        fileName:
                - particleGun_E100.root
        legTitle:
                - "convertion events included"
                - "convertion events excluded"
                # - "convertion events required"
                - "photon reclustering"
                # - "photon+neutral reclustering"
                # - "photon+neutral reclustering (looser theta cut)"
        histName: 
                - eventHists/efficiencyVsCosTheta
                - eventHists_noConv/efficiencyVsCosTheta
                # - eventHists_conv/efficiencyVsCosTheta
                - eventHists_photonRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl/efficiencyVsCosTheta
                # - eventHists_photonAndNeutralRecl_looseThetaCut/efficiencyVsCosTheta
        legPos:
                - 0.12
                - 0.7
                - 0.68
                - 0.9
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        # xAxisRange:
        #         - 0
        #         - 120
        yAxisRange:
                - 0.0
                - 1.5
        histTitle: "E_{#gamma}=100 GeV"
        # legCaptionMode: entries
        # logY: 1
        rebinFactor: 4
        scaleFactor: 0.25
        drawOptions: H
