eff_vs_theta:
        dirPrefix: /afs/cern.ch/work/v/viazlo/analysis/PFAAnalysis/build/PhotonECAL/FCCee_singleParticle_performace/kaon0L/nominalEfficiency/
        fileName:
                - ratioFile.root 
        legTitle:
                - 10 GeV
                - 50 GeV
        histName: 
                - particleGun_E50_Theta0_Phi0
        legPos:
                - 0.15
                - 0.2
                - 0.35
                - 0.3
        histColor:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
        xAxisRange:
                - 35
                - 60
        yAxisLabel: Efficiency
        histTitle: ""
