pfo_type_map:
        electron: 11
        muon: 13
        gamma: 22
        photon: 22
        pion: 211
        neutral: 2112
        Electron: 11
        Muon: 13
        Gamma: 22
        Photon: 22
        Pion: 211
        Neutral: 2112

