energy_firstEnergeticPartOfType:
        histNamePrefix: firstEnergeticPartOfType_
        histNamePostfix: Energy
        histNameBase: 
                - noAdditionalPFOs 
                - thereAreAdditionalPFOs
        histLegend: 
                - one reconstructed PFO
                - 2 or more reconstructed PFOs
        rebinFactor: 1
        histColor: 
                - 1 
                - 2
        xAxisRange: 
                - 0 
                - 15
        legPos:
                - 0.25
                - 0.8
                - 0.75
                - 0.9
phi_firstEnergeticPartOfType:
        histNamePrefix: firstEnergeticPartOfType_
        histNamePostfix: Phi
        rebinFactor: 10
        histNameBase: 
                - noAdditionalPFOs 
                - thereAreAdditionalPFOs
        yAxisRange: 
                - 0 
                - 1000
ECAL_EnergyPerLayers_barrelVsEndcap:
        customInFileDirOrHistName: True
        histNameBase: 
                - ECALBarrel/CAL_EnergyPerLayers
                - ECALEndcap/CAL_EnergyPerLayers
        yAxisRange:
                - 0
                - 1000
HCAL_EnergyPerLayers_barrelVsEndcap:
        customInFileDirOrHistName: True
        histNameBase: 
                - HCALBarrel/CAL_EnergyPerLayers
                - HCALEndcap/CAL_EnergyPerLayers
        yAxisRange:
                - 0
                - 1000
dPhi_secondEnergeticPFO:
        histNamePrefix: signalPFO_
        histNamePostfix: _dPhi
        histNameBase: 
                - secondEnergeticPFO 
        xAxisRange: 
                - -40 
                - 40
type_firstEnergeticNeutralPFO:
        customInFileDirOrHistName: True
        histNameBase: 
                - PandoraPFOs_22_2112/firstEnergeticPartOfType_Type
rawEnergy_ECAL:
        customInFileDirOrHistName: True
        rebinFactor: 2
        xAxisRange: 
                - 0 
                - 60
        yAxisRange:
                - 0
                - 250
        histNameBase:
                - ECALBarrel/CAL_Energy
                - ECALEndcap/CAL_Energy
        histColor: 
                - 1 
                - 2
        histLegend: 
                - ECAL Barrel
                - ECAL Endcap
        legPos:
                - 0.6
                - 0.7
                - 0.9
                - 0.9

rawEnergy_HCAL:
        customInFileDirOrHistName: True
        rebinFactor: 2
        xAxisRange: 
                - 0 
                - 60
        yAxisRange:
                - 0
                - 250
        histNameBase:
                - HCALBarrel/CAL_Energy
                - HCALEndcap/CAL_Energy
        histColor: 
                - 1 
                - 2
        histLegend: 
                - HCAL Barrel 
                - HCAL Endcap
        legPos:
                - 0.6
                - 0.7
                - 0.9
                - 0.9


